name: 打声招呼
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    name: 如果是初次见面…
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        issue-message: '你好，欢迎来到 Taichi 中文社区！'
        pr-message: '翻译辛苦了！请休息一会，审核菌马上就来……'
